# Kustomize 설정 - 모든 리소스를 mesh-demo 네임스페이스에 배포
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mesh-demo
resources:
  - namespace.yaml
  - ui.yaml
  - api.yaml
  - details.yaml
  - ratings.yaml
